### ISSUE TITLE
Slow point loading from gpkg in Leaflet

### ISSUE THREAD

**Issue by sweco-sekrsv** [ngageoint/geopackage-js#107]
Hi!

Thanks for making this library, I really like the idea of working with geopackage in Leaflet! I tried loading a point set with about 72k points and have run into load performance issues. It takes several minutes to display all the points. And it seems that points are loaded in random order and not within the current bound. I guess Im doing something wrong.

For example in Qgis the geopackage file loads and displays instantly. Any ideas on how to load the point features quicker? 

I attached a working example (zip) file here for anyone to look at and debug. The geopackage are generated with a spatial index. The gpkg file in the example is generaed from Qgis 3 but I also tried with the same dataset using gdal but with the same results.

Thanks!
[geop.zip](https://github.com/ngageoint/geopackage-js/files/1808185/geop.zip)

**Comment by danielbarela** [comment]
I ran your sample program and it appears that everything is working within about 15 seconds.  I loaded your sample GeoPackage into http://ngageoint.github.io/geopackage-js/ on Safari and it also took approximately 15 seconds.  What browser are you using?  The points are loaded in whatever order the database gives them back in.  We do not (currently) sort on distance from the map viewport or anything fancy like that.

![manypointsload](https://user-images.githubusercontent.com/1648929/37364190-735e1198-26bf-11e8-866c-1ac1842d3243.gif)

**Comment by kristiansvenssonwsp** [comment]
Thanks for the super speedy response, really appreciated!

Wow thats fast and really something I was looking for speedwise. Im using Chrome(65.0.3325.146). Using the service you linked it halts Chrome for about a couple of minutes and then crashes the tab. I noticed RAM usage was very high.

I just tried in Firefox (59.0) as well, it loads in about 15 sec, RAM usage of about 1.3 GB. Navigation is not very smooth but maybe thats Leaflets problem:) Are you using Leaflet for that link?

Also tried in Edge (41.16299.248.0). It does not load any point features(waited more than 5 minutes).

**Comment by danielbarela** [comment]
I also tried Chrome 64.0.3282.140 on my Mac and it worked in approximately the same time as Safari.  I don't know what could possibly be crashing Chrome.  Also ran on Chrome 64.0.3282.119 on a Windows VM which managed to load the GeoPackage in about 25 seconds.  The GeoPackage is not even that big, 72k points is a lot but not enough that should cause memory issues.  I can't speak to how the page runs in Edge, but I would imagine not well, I bet there is some JavaScript error.  I can try to track down what is going on there.
