### ISSUE TITLE
proj4 is not a function in TileDao.js

### ISSUE THREAD

**Issue by sveta-wl** [ngageoint/geopackage-js#112]
Hi guys,

I've recently got an issue probably connected in some way to this one https://github.com/ngageoint/geopackage-js/issues/103. In the file TileDao.js in the function TileDao.prototype.initialize occurs the following error:
proj4 is not a function

The code line from the fix of the issue https://github.com/ngageoint/geopackage-js/issues/103
`proj4 = 'default' in proj4 ? proj4['default'] : proj4; `
solves the problem. 
Would it be possible/right solution to provide this hack in the package?

**Comment by danielbarela** [comment]
Sorry about that.  Found and fixed all instances of this issue.  I will release a new version shortly.

**Comment by danielbarela** [comment]
Fixed in v1.1.1

**Comment by sveta-wl** [comment]
That's great, Thank you!
