### ISSUE TITLE
proj.Proj4 is not a function in converters

### ISSUE THREAD

**Issue by dylrich** [ngageoint/geopackage-js#117]
No matter how I import the provided converter modules into my project (building with webpack), I get an error from the .addLayer method of the shapefile converter that proj4.Proj is not a function. I've tried explicitly importng proj4 with no luck. I am developing on Fedora Linux, if that makes any difference. The GeoPackageAPI works fine for me, but none of the converters work. Any hints or instructions on grabbing more useful information from my end would be most appreciated.

**Comment by danielbarela** [comment]
Looks like I missed a check for proj4 in the shapefile converter. I can add it in on Monday but in the meantime you can add this line after the require imports (just before the addLayer function definition:

proj4 = 'default' in proj4 ? proj4['default'] : proj4;


Let me know if that helps.

**Comment by dylrich** [comment]
Hey, thanks much for the quick response! That fix appears to have done it and I threw in a pull request.
