### ISSUE TITLE
UI Block with zoom map

### ISSUE THREAD

**Issue by dragonmaster81** [ngageoint/geopackage-js#12]
In the browser with the index.html, when I change the zoom ui is block up to all the tiles are loaded.
I have see.
i have seen a leaflet example:
https://github.com/aparshin/leaflet-fractal
the function drawTile do a long work but the ui is not block maybe this can help you.

**Comment by danielbarela** [comment]
Thanks @dragonmaster81 for the suggestion.  I will create a ticket to use Web Workers to draw the images which is what is being done in the example you provided. #14
