### ISSUE TITLE
getTile for different projections

### ISSUE THREAD

**Issue by sveta-wl** [ngageoint/geopackage-js#121]
Hi guys,

I'm trying to display tiles from some geopackage, which has srs EPSG:31467 and it doesn't work. 
I use your code example from the project description to get tiles. It works perfectly for rivers.gpkg from the example and also for other geopackages, which have srs EPSG:4326 or EPSG:3857. 
What should I do to get another projections work? Could you please help me?

**Comment by danielbarela** [comment]
I believe that you are going to want to use this method: GeoPackageTileRetriever.getTileWithWgs84BoundsInProjection  That takes a latitude longitude bounding box, the zoom level you want, and a target projection ('EPSG:31467').

If you could provide me with the GeoPackage you are trying to use and the sample of code you are using I can take a look.
