### ISSUE TITLE
Tiles only rendering at zoom level 3

### ISSUE THREAD

**Issue by zacharyburnett** [ngageoint/geopackage-js#123]
I have a geopackage with a `tiles`-type table, made by coercing `float32` data into `uint8`. However, the tiles are not rendered on a leaflet map on any zoom level except for zoom 3. For every other zoom level, it shows `Draw tile` messages, but no rendering.

Here is the geopackage I am using:

https://drive.google.com/open?id=1ctWt2L-im8gzwge-Nft90C4NXzpbVdu0

**Comment by danielbarela** [comment]
Your GeoPackage only has tiles for zoom level 3.

**Comment by zacharyburnett** [comment]
Sorry for wasting your time.
