### ISSUE TITLE
Is it possible to write a geopackage file?

### ISSUE THREAD

**Issue by Renaud009** [ngageoint/geopackage-js#125]
I am trying to generate a geopackage file based on multiple drawn features in a layer using OpenLayers 5 Draw class. Could you provide me any example or interesting class methods for such a task?

Thanks in advance

**Comment by wallw-bits** [comment]
Yes. I don't have a simplified example right now, but the gist is to use OL's `GeoJSON` format and then call `addGeoJSONFeatureToGeopackage(gpkg, geojson, tablename)`.

Not so simplified example from the worker we use here (the highlighted line and the three functions that follow): https://github.com/wallw-bits/opensphere-plugin-geopackage/blob/master/src/worker/gpkg.worker.js#L425
