### ISSUE TITLE
Add tutorial for openlayers intergration

### ISSUE THREAD

**Issue by HarelM** [ngageoint/geopackage-js#127]
I was hoping to be able to present geopackage on my website using openlayers.
Looking at the documentation and using google search did not allow me to find how to use this library with openlayers.
Is it possible to add a tutorial to the documentation to show what needs to be done in order to make openlayers present geopackage tiles?

**Comment by danielbarela** [comment]
I have not worked with OpenLayers however there are many convenience methods in the API that should help: getTileFromXYZ for 3857 tiles, draw4326TileInCanvas for 4326 tiles, in addition to the query for GeoJSON methods.  If you would like to contribute a tutorial, I will accept the pull request.

**Comment by danielbarela** [comment]
Documentation for the library can be found here: http://ngageoint.github.io/geopackage-js/jsdoc/module-GeoPackage-GeoPackageAPI.html
You can find an example of how to use those methods to integrate with Leaflet here: https://github.com/ngageoint/geopackage-js/blob/master/leaflet/leaflet-geopackage.js
I will re open this issue in the hopes that someone can provide a tutorial.

**Comment by danielbarela** [comment]
This appears to have been implemented in an example here: https://labs.webgeodatavore.com/partage/trails/
Source: https://twitter.com/ThomasG77/status/1090054950074359808

**Comment by ThomasG77** [comment]
In fact, the previous link provided is for untiled vector layers.
For raster tiles, see https://labs.webgeodatavore.com/partage/gpkg-raster-tiles/
PS: I'm the author of both samples.

**Comment by ThomasG77** [comment]
Only remaining demo would be vector tiles. I will maybe play with it later :)

**Comment by xirias** [comment]
Thomas, I'm running Chrome and those samples don't work on my machine.  The vector sample gives an error about not loading geopackage.  The tile sample doesn't explicitly produce an error but shows no data either.

**Comment by ThomasG77** [comment]
@xirias No clue. The examples are working on Chrome Version 72.0.3626.81 and Firefox 65 (64 bits) on Linux.
Only clue could be you have a plugin that block also some network calls. Open samples in a browser private window to try out.

**Comment by HarelM** [comment]
@ThomasG77 Thanks for the info!!
The main thing that I haven't found any info about is how to convert the geopackage styles to openlayer styles mainly for the use cause of map rotation and keeping the text aligned.
If you get this working it would be support if you could post a link here.
Keep up the good work!

**Comment by danielbarela** [comment]
GeoPackage does not (currently) have a way to define styles within the GeoPackage.

**Comment by HarelM** [comment]
Really? Then how does the rendering works if the styles are not defined inside the file? Are they defined elsewhere?

**Comment by danielbarela** [comment]
It is left up to the clients to decide how to render each vector layer.  The demo page just renders the vectors in a shade of blue.  I believe the OGC is working on a style extension, but I am not sure what the progress is on that.

**Comment by HarelM** [comment]
I've seen the below two articles where it is suggested that some GeoPackage creators are doing this, but it might not be a standard, did I get this right? using a table called `layer_styles`...?
https://www.geocat.net/extending-geopackage-to-include-projectstyling-information/
https://gis.stackexchange.com/questions/273750/is-there-any-way-to-include-universal-style-symbology-in-geopackage

**Comment by ThomasG77** [comment]
Styles are in your code in OpenLayers.
There are extensions in Geopackage to support styling https://www.geopackage.org/extensions.html. One is vendor related (QGIS), another is tied to OWS Context.
The only possible move for styles with these extensions would be to support conversion from QGIS or SLD styles to OpenLayers styles. I'm not aware of "out of the box" solutions for this intent.

**Comment by HarelM** [comment]
I found this package:
https://github.com/Norkart/SLDexit
Which can be used to convert SLD to mapbox gl style
And this one:
https://github.com/openlayers/ol-mapbox-style
From mapbox gl to openlayers.
I haven't tried it myself but it's an interesting idea I've read somewhere...

**Comment by elwoodhouse** [comment]
@ThomasG77 is the https://labs.webgeodatavore.com/partage/trails/ sample still available somewhere? Or did anyone else grab a copy of it that can share it?

Thanks.

**Comment by ThomasG77** [comment]
@elwoodhouse Restored the broken url
