### ISSUE TITLE
Raster tiles not displayed

### ISSUE THREAD

**Issue by galfar** [ngageoint/geopackage-js#143]
Viewer at http://ngageoint.github.io/geopackage-js (is it the version in master?) stopped displaying raster tiles from GeoPackages, not even rivers.gpkg.
I remember just a few weeks ago it worked fine.

Error message in browser console:
```
TypeError: GeoPackageAPI.drawXYZTileInCanvas is not a function
in createTile http://ngageoint.github.io/geopackage-js/common.js:498
```

**Comment by danielbarela** [comment]
Sorry about that, I am updating the API and did not update the viewer call.  Fixed now.

**Comment by galfar** [comment]
Great, thanks.
I think there's still one problem though with the list of tiles in the current view ("Tiles" tab) always saying "No tiles exist in the GeoPackage for the current bounds and zoom level" and not listing any tiles.

**Comment by danielbarela** [comment]
I will look into that.  Thanks.

**Comment by danielbarela** [comment]
@galfar I found the issue and it is working again.  Please let me know if you find anything else.

**Comment by galfar** [comment]
All looks fine now, thanks.
