### ISSUE TITLE
cannot use geopackage-js in react-native

### ISSUE THREAD

**Issue by chtk3131** [ngageoint/geopackage-js#145]
Hi

I'm thinking of using geopackage-js in react-native.
However, the installation of the module by NPM has caused many errors and has not been able to run it. 

For example, I get the following error
・`Unable to resolve "../build/better_sqlite3.node" from "node_modules\better-sqlite3\lib\database.js"`

・`Unable to resolve "../build/integer.node" from "node_modules\integer\lib\index.js"`

・`The package at "node_modules\@ngageoint\geopackage\node_modules\image-size\dist\index.js" attempted to import the Node standard library module "fs". It failed because React Native does not include the Node standard library.`

・`ffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`
⇒Added the `max-old-space-size=4096` option, but it didn't finish the process. (Is there a loop going on?)

etc..

Incidentally, I use `rn-nodeify` appropriately to install the necessary packages.

Is it better not to think about using it in react-native?
Do you have any plans to support react-native?
If you have a sample that uses react-native, can you tell me about it?

thankyou

**Comment by danielbarela** [comment]
I have never used react-native.  If you could provide me a sample project and instructions I can look into what is going on.  Thanks.

**Comment by chtk3131** [comment]
> I have never used react-native. If you could provide me a sample project and instructions I can look into what is going on. Thanks.

Thanks for the reply.

The project I created is a project I created according to the introduction of react-native, with geopackage-js installed.
Other than that, I didn't do anything particularly special.

A simple project can be created as per the introduction in the link below.
https://reactnative.dev/docs/environment-setup

I've tried both "Expo CLI Quickstart" and "React Native CLI Quickstart".

The installation of geopackage-js was done with YARN.
yarn add @ngageoint/geopackage

Thanks.

**Comment by danielbarela** [comment]
I will take a look at this when I get a chance.

**Comment by chtk3131** [comment]
> I will take a look at this when I get a chance.

thanks.
I am very troubled.
I look forward to hearing from you about the solution.

**Comment by danielbarela** [comment]
OK, I took a cursory look at this and as far as I can tell, react native does not support standard node libraries like path etc.  When I build for the web, I use browserify to properly include the web versions of these packages.  I am unsure if there is a way to do that in react native.  I, personally, have never had any good experiences with write once run anywhere type frameworks, but that does not mean it cannot be done or is not a good idea.

I would just say, if you are writing a web app, or a node app, use this library.  If you are writing an iOS app, use http://ngageoint.github.io/geopackage-ios/ if you are writing an Android app, use http://ngageoint.github.io/geopackage-android/

If you continue down this path, and do end up figuring anything out, please let me know.  BTW I have a new version of this library coming, which is written in TypeScript and depends on a newer build of better-sqlite3 which is precompiled.  To install it, just run ```npm install @ngageoint/geopackage@beta --save```

Sorry I couldn't be much help, I just have never used react native and am unsure of its capabilities or how to include regular node packages like fs and path.

**Comment by chtk3131** [comment]
@danielbarela 

Thank you very much for the verification.
It may be difficult after all.

Using rn-nodeify, you can use the
"browserify", "fs", "path" and other packages can be included for react-native.
https://github.com/tradle/rn-nodeify.

I've been able to eliminate some of the errors that were occurring during package installation by using rn-nodeify.
I hope this is useful information.
