### ISSUE TITLE
Cannot find @ngageoint/geojson-to-geopackage on npmjs.com

### ISSUE THREAD

**Issue by oncletom** [ngageoint/geopackage-js#146]
Hello,

Thanks a lot for the tool!
I discovered a reference to a GeoJSON to GPKG tool in the `converters/geojson` folder. But I cannot find any reference to a package named `@ngageoint/geojson-to-geopackage` on npm.

Is that intentional?

**Comment by danielbarela** [comment]
It is not.  I am currently upgrading everything to TypeScript.  Things are a bit hectic at the moment but I will try to carve out some time to update the converter and get it published to NPM.

**Comment by oncletom** [comment]
Okay, understood!

I will subscribe to new releases to be notified when it happens.

No rush — I can use `ogr2ogr` in the meantime.
Thanks for replying so promptly, and take care.

**Comment by oncletom** [comment]
Okay, understood!

I will subscribe to new releases to be notified when it happens.

No rush — I can use `ogr2ogr` in the meantime.
Thanks for replying so promptly, and take care.
