### ISSUE TITLE
SLD to FeatureStyle?

### ISSUE THREAD

**Issue by fjenett** [ngageoint/geopackage-js#159]
Hi, currently QGIS will store styles as SLD in a table called "layer_styles" in a geopackage. Is there a way to transform these settings to FeatureStyles?

**Comment by danielbarela** [comment]
As far as I know, QGIS is utilizing this extension: https://github.com/pka/qgpkg/blob/master/qgis_geopackage_extension.md
We currently do not implement that extension, but would welcome a pull request which implements it.  That extension would have to be implemented, along with QML and SLD parsing to be able to translate the styles into the FeatureStyle extension.  This library works both in node and the browser which complicates this further.
