### ISSUE TITLE
Raster geopackage

### ISSUE THREAD

**Issue by rafaalbert** [ngageoint/geopackage-js#168]
I've tred to load a raster geopackage but I had this error: doneCallback is not a function. How can I solve it?

**Comment by danielbarela** [comment]
Where were you trying to do this?

**Comment by rafaalbert** [comment]
I have created my geopackage in qgis using a .tiff image. And tried this:

`var placer = L.geoPackageFeatureLayer([], {
    geoPackageUrl: 'code/002.gpkg',
    layerName: 'raster',

}).addTo(map);`

**Comment by rafaalbert** [comment]
oh, yes. But now I have bunch of lines with the same error: file is not a database. Maybe I'm missing somethng when I create the geopackage in QGIS cos I used a points layer from tutorial and it works fine, but after I had this error with my raster I've created a point layer and it doesn't work

**Comment by danielbarela** [comment]
Have you tried loading your GeoPackage here: https://ngageoint.github.io/geopackage-js/ If it does not work there, I can look at it if you put it somewhere I can get to.

**Comment by rafaalbert** [comment]
I have tried right now and it was loaded fine

![imagen](https://user-images.githubusercontent.com/6163375/104232294-c3259a80-5415-11eb-9e3d-ca221c867d4f.png)

**Comment by danielbarela** [comment]
Your layer is named 002
```
const tileLayer = L.geoPackageTileLayer({
  geoPackageUrl: 'code/002.gpkg',
  layerName: '002',
}).addTo(map);
```

**Comment by rafaalbert** [comment]
Yeii, it woks XD . thanks for the support. I have a final question, how can I zoom to the tile?

**Comment by danielbarela** [comment]
Assuming that QGIS set the tile matrix set bounding box correctly, you can do this (replace my GeoPackage and layer names with yours):
```
const tileLayer = L.geoPackageTileLayer({
  geoPackageUrl: 'https://ngageoint.github.io/GeoPackage/examples/rivers.gpkg',
  layerName: 'rivers_tiles',
}).addTo(map);

tileLayer.on('load', function() {
  tileLayer.off('load');
  const tileDao = tileLayer.geoPackage.getTileDao('rivers_tiles');
  const projectedBoundingBox = tileDao.tileMatrixSet.boundingBox.projectBoundingBox(tileDao.projection, 'EPSG:4326');
  map.fitBounds([
    [projectedBoundingBox.minLongitude, projectedBoundingBox.minLatitude],
    [projectedBoundingBox.maxLongitude, projectedBoundingBox.maxLatitude],
  ]);
```

**Comment by rafaalbert** [comment]
Great. I'm very grateful with your help. Now it works perfectly. Thank you
