### ISSUE TITLE
Update feature geometry

### ISSUE THREAD

**Issue by berkayoruc** [ngageoint/geopackage-js#170]
Hello developers. I want to update geometry of feature but I cannot find any method about it. Is it possible update local file or how can I do that? I try 
```
GeopackageConnection.run("DELETE FROM kat_planlari WHERE mslink=5274")
``` 
and error is no such module: rtree

![image](https://user-images.githubusercontent.com/22800134/105997267-794ade80-60bc-11eb-9ce9-386d779e8546.png)

> I can open and change some features of gpkg in QGIS

**Comment by danielbarela** [comment]
It appears that the sqljs version you are using does not include rtree in the build.  How did you build this?

**Comment by berkayoruc** [comment]
sqljs version is 1.4.0.

**Comment by danielbarela** [comment]
You can't use that version.  Sql.js made the decision to not include rtree in the build (see: https://github.com/sql-js/sql.js/issues/59 ).  I had to create a new package and publish it, so you must use rtree-sql.js v 1.0.0

**Comment by berkayoruc** [comment]
Oh thank you. But this update function or update sql statement affect local gpkg or just virtual gpkg?

**Comment by danielbarela** [comment]
If you are using a browser, and consequentially sql.js, everything is read into memory, which is also where the changes are made if you run any update statements.  After you have made your changes, to save the file, you will have to do something like this:
```
window.saveGeoPackage = function() {
  geoPackage.export(function(err, data) {
    fileName = fileName || 'geopackage.gpkg';
    saveByteArray([data.buffer], fileName.substring(0, fileName.lastIndexOf('.')) + '.gpkg');
  });
};

const saveByteArray = (function() {
  const a = document.createElement('a');
  document.body.appendChild(a);
  a.style = 'display: none';
  return function(data, name) {
    const blob = new Blob(data, { type: 'octet/stream' }),
      url = window.URL.createObjectURL(blob);
    a.href = url;
    a.download = name;
    a.click();
    window.URL.revokeObjectURL(url);
  };
})();
```

**Comment by berkayoruc** [comment]
Yes, I am developing for browser. So, it is not efficient way usign gpkg or any local files to editing.
