### ISSUE TITLE
Getting tiles from a bounding box

### ISSUE THREAD

**Issue by GuittonHubert** [ngageoint/geopackage-js#189]
Hello,

I was expecting to get a tile (or a set of tiles) covering an input bounding over its whole surface when using code like that:

```
var wgs84BoundingBox = new BoundingBox(0, 0, 90, 66.51326044311185);
var gpr = new GeoPackageTileRetriever(tileDao, 256, 256, 'image/png');
gpr.getTileWithBound(wgs84BoundingBox, Projections.getWGS84Projection());
```

But the result is a single tile covering partially the bounding box. Is there a way to generate the expected tile from a combination of tiles in the matrix set using the current API? Thank you for your help.

Have a nice day,

Hubert

**Comment by danielbarela** [comment]
The result of that call should be 1 tile that covers the bounding box provided.
