### ISSUE TITLE
Add data to existing GeoPackage

### ISSUE THREAD

**Issue by eclosion2012** [ngageoint/geopackage-js#190]
Is there a example for add data to exisiting geopackage?Now,the new feature is not update to the gpkg file when i use the "featureDao.create()" method?

**Comment by danielbarela** [comment]
This function is an example of how to insert feature data into the geopackage.

https://github.com/ngageoint/geopackage-js/blob/23eb4cef605bec959dbff51fef1400ab9909c21e/test/geopackageUtils.js#L66

**Comment by eclosion2012** [comment]
> This function is an example of how to insert feature data into the geopackage.
> 
> https://github.com/ngageoint/geopackage-js/blob/23eb4cef605bec959dbff51fef1400ab9909c21e/test/geopackageUtils.js#L66

thank you

**Comment by eclosion2012** [comment]
thank you.




雪落无声
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ngageoint/geopackage-js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月27日(星期四) 凌晨3:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ngageoint/geopackage-js] Add data to existing GeoPackage (Issue #190)





 
This function is an example of how to insert feature data into the geopackage.
 
https://github.com/ngageoint/geopackage-js/blob/23eb4cef605bec959dbff51fef1400ab9909c21e/test/geopackageUtils.js#L66
