### ISSUE TITLE
Support for new OGC GPKG Extensions to support Vector Tiles PBF

### ISSUE THREAD

**Issue by techmavengeospatial** [ngageoint/geopackage-js#192]
Is there plans to extend this library to support GeoPackage Vector Tiles?
https://www.geopackage.org/extensions.html
https://gitlab.com/imagemattersllc/ogc-vtp2/-/tree/master/extensions

We've Updated Tile Utilities Desktop app https://portfolio.techmaven.net/apps/tile-utilities/
to support conversion of mbtiles vector tiles to gpkg vector tiles

**Comment by danielbarela** [comment]
We currently do not have resources allocated to support that community extension.  If you would like to add support for that extension and submit a pull request, we would be happy to accept it.
