### ISSUE TITLE
How can i convert MBTile to Geopackage in the command line?

### ISSUE THREAD

**Issue by adriansuciu09** [ngageoint/geopackage-js#194]
I am trying to write a script that converts MBTile foiles to Geopackage in a Docker container. I need to be able to convert the data in a command line. Is it possible to do that with this project?

**Comment by danielbarela** [comment]
This library is an API that allows you to write any application you would like to interact with and build GeoPackages.  There is no reason you shouldn't be able to write a command line node application to do what you want.
