### ISSUE TITLE
Problem on Checking Column Max in GeoPackage.js

### ISSUE THREAD

**Issue by pasx** [ngageoint/geopackage-js#27]
I am trying to run the demo locally and using the .js contained in the static folder.

![image](https://cloud.githubusercontent.com/assets/11922040/17056519/1514a0da-5014-11e6-80ad-d88e649d4e7b.png)

It looks like the function validateMax is checking on the numeric dataType and not the type name so should be implemented as:

if(this.max && this.dataType !== 9...
instead of
if(this.max && this.dataType !== 'TEXT'...

The type is passed in to FeatureTableReader.prototype.createColumnWithResults where it is converted to a numeric dataType so validateMax will never receive it.

UserColumn.call is used in two places: for FeatureColumn and TileColumn, the second call also passes on the numeric datatype so the check in validateMax definitely looks wrong.

**Comment by danielbarela** [comment]
Sorry about that.  The fix for that bug was sitting in develop.  I have pulled the fix up to the master branch.
