### ISSUE TITLE
mbtiles

### ISSUE THREAD

**Issue by techmavengeospatial** [ngageoint/geopackage-js#55]
It would be great to also preview mbtiles
don't need to make mbtiles but load an mbtiles with tile_data with PNG or JPG tiles

separately, it would also be great to preview vector tiles mbtiles with PBF in tile_data

**Comment by danielbarela** [comment]
I am currently working on the MBTiles to GeoPackage converter.  I will keep this thread updated with progress.

**Comment by geospatialmapmashup** [comment]
Would like to also just view mbtiles just like geopackage tiles.  Without nodejs dependency. Just client side Javascript
