### ISSUE TITLE
Do not require primary key on tiles table

### ISSUE THREAD

**Issue by MartinMikita** [ngageoint/geopackage-js#68]
Hi,

Would be possible to set default primary key column as `id` in GeoPackage?
We are creating GPKG tiles as view, and there is not possible to set primary key index.

Now I receive this backtrace:
```
Uncaught Error: No primary key column was found for table 'package_tiles'
    at TileTable.UserTable (gp.js:48931)
    at new TileTable (gp.js:48364)
    at TileTableReader.createTableWithNameAndColumns (gp.js:48485)
    at TileTableReader.<anonymous> (gp.js:49096)
    at gp.js:38813
    at gp.js:38840
    at gp.js:50009
    at gp.js:49387
    at gp.js:38811
    at gp.js:38835
```

This GPKG can't be opened in your JS.

I have tried to change it in [commit in the fork](https://github.com/MartinMikita/geopackage-js/commit/d0a18354259df0c9552a5813d786961bdead1e2d), but now I receive this error backtrace:

```
Uncaught TypeError: Cannot read property 'name' of undefined
    at TileDao.UserDao (gp.js:48597)
    at new TileDao (gp.js:47819)
    at GeoPackage.<anonymous> (gp.js:40721)
    at TileTableReader.<anonymous> (gp.js:49129)
    at gp.js:38841
    at gp.js:38868
    at gp.js:50041
    at gp.js:49419
    at gp.js:38839
    at gp.js:38863
```

**Comment by danielbarela** [comment]
Can you please provide an example GeoPackage that fails to open?

**Comment by MartinMikita** [comment]
If it helps you with fixing the request, here it is:
http://labs.klokantech.com/miki/test-mercator.gpkg

**Comment by danielbarela** [comment]
Thanks, I'll take a look and keep you updated.

**Comment by danielbarela** [comment]
I have pulled the fixes for this into master.  Please let me know if this doesn't correct the issue you are seeing.
