### ISSUE TITLE
Display MapBox PBF Vector Tiles (mbtiles tile_data blob contains pbf)

### ISSUE THREAD

**Issue by geospatialmapmashup** [ngageoint/geopackage-js#70]
display mbtiles that are vector tiles on map

**Comment by danielbarela** [comment]
Converting MapBox PBF Vector Tiles to GeoPackage is being worked.  Progress will be updated here.

**Comment by danielbarela** [comment]
This is not complete.  Working out bugs.

**Comment by danielbarela** [comment]
OK, I think this is better now.
