### ISSUE TITLE
leaflet-geopackage build problems

### ISSUE THREAD

**Issue by jsuwala** [ngageoint/geopackage-js#89]
Hi!

Thanks for your work on leaflet-geopackage; it's great to see this integration between leaflet and geopackage-js working.

I thought I should report two problems with your current package.json that I found when trying to compile leaflet-geopackage:

1. the webworkify package is missing (I got the error `"Error: Cannot find module 'webworkify' from '/home/user/geopackage/leaflet/node_modules/geopackage/lib/tiles/creator'"`)
2. the default uglify-js installed does not support es6, so gives the error `"uglifyjs failed: SyntaxError: Unexpected token: operator (>)"`.

A fix to the missing webworkify package is straight-forward.

And I found a fix for the uglify-js problem here: https://github.com/driftyco/ionic/issues/8817 , which says you need to reference the "harmony" branch of uglify-js.

The revised package.json file that includes these two fixes is attached.

- Jason
[package.json.txt](https://github.com/ngageoint/geopackage-js/files/904208/package.json.txt)

**Comment by danielbarela** [comment]
I added webworkify but I cannot make the syntax error occur.  What did you run to make that happen?
Thanks

**Comment by jsuwala** [comment]
I was just running npm commands:
1: `npm install`

> `"Error: Cannot find module 'webworkify' from '/home/user/geopackage/leaflet/node_modules/geopackage/lib/tiles/creator'"`

2:  `npm install webworkify --save`
3: `npm run build-min`

> `Parse error at -:20762,24
module.exports = input => {
                        ^
SyntaxError: Unexpected token: operator (>)`

I'm running Ubuntu 14.04.5 LTS, with npm version 4.0.5

**Comment by danielbarela** [comment]
AH, npm 4.0.5 was the key.  Added in your uglify fix and merged to master.
Thanks
