### ISSUE TITLE
Error running npm install 

### ISSUE THREAD

**Issue by gotnull** [ngageoint/geopackage-js#90]
![screen shot 2017-07-25 at 11 15 28 am](https://user-images.githubusercontent.com/578908/28551330-a595f108-712a-11e7-8c00-86b121fc88db.png)
![screen shot 2017-07-25 at 11 15 25 am](https://user-images.githubusercontent.com/578908/28551331-a5c10af0-712a-11e7-8321-9cc1b8991f0b.png)

**Comment by gotnull** [comment]
I think it's related to this:

https://github.com/EyalAr/lwip/issues/263

**Comment by danielbarela** [comment]
I will investigate changing the lwip library for something else and update progress here.

**Comment by danielbarela** [comment]
Published 1.0.19 to remove lwip.
