### ISSUE TITLE
featureDao.queryIndexedFeaturesWithWebMercatorBoundingBox method returns only geom value

### ISSUE THREAD

**Issue by adjioev** [ngageoint/geopackage-js#92]
Hello, 

I found that `featureDao.queryIndexedFeaturesWithWebMercatorBoundingBox(bbox, callback, done)` function is returning rows with geom column only, skiping any other props. 

I did some debugging and found that geopackage js is executing below query:
```
select rivers.geom 
from 'nga_geometry_index' inner join rivers on rivers.id = nga_geometry_index.geom_id 
where nga_geometry_index.table_name = 'rivers' and 
		nga_geometry_index.min_x <= -12863648.645994272 and 
		nga_geometry_index.max_x >=  -12865751.85860068  and 
		nga_geometry_index.min_y <=  6655573.571054254 and 
		nga_geometry_index.max_y >= 6651886.678768059
		
```

when it should be `select *`.

If you check FeatureTableIndex.js it says 
'  this.geometryIndexDao.queryJoinWhereWithArgs(join, where, whereArgs, [this.tableName + '.' + this.featureDao.getGeometryColumnName()], rowCallback, doneCallback);'

i.e. columns = this.tableName + '.' + this.featureDao.getGeometryColumnName() => rivers.geom

If i'm not wrong, fix should be something like this
'  this.geometryIndexDao.queryJoinWhereWithArgs(join, where, whereArgs, '*', rowCallback, doneCallback);'

Thanks Alex

**Comment by danielbarela** [comment]
Published 1.0.22 which fixes this bug.  Thank you for the detailed bug and your fix was the correct fix.
