### ISSUE TITLE
featureDao.create() doesn't update nga_geometry_index

### ISSUE THREAD

**Issue by adjioev** [ngageoint/geopackage-js#94]
Hi guys,

I insert feature into geopackage with addGeoJSONFeatureToGeoPackage() method that calls featureDao.create(featureRow, callback). The problem is that create() insert row but doesn't update nga_geometry_index.

Because  I use featureDao.queryIndexedFeaturesWithWebMercatorBoundingBox() to render features whatever was created is not visible on the map.

From my point, nga_geometry_index table might become a pain in the neck, as you have to keep it in sync with all tables and update it on every feature CRUD operation.  And if someone does changes via sqlbrowser app table will be also out of sync.

Thanks Alex

**Comment by danielbarela** [comment]
I created a new method on GeoPackage called addGeoJSONFeatureToGeoPackageAndIndex which will keep the index up to date with each insert of a new feature via this method.
