### ISSUE TITLE
Looking for a bit of help getting package installed

### ISSUE THREAD

**Issue by MCR01** [ngageoint/geopackage-js#96]
Hello,

I know this is probably a simple question but I am going to ask anyway.

Do I need to use NPM to build the package?(As might not be able to install on work computer) 

I am trying to setup a simple webpage (Just a map for now) and display my GIS info (gpkg's). I have the basemap displaying but when I try to load layers nothing shows up.

Any help to point me the right direct would be great. 

Current code encase you want to see it.

             
```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Leaflet Map with a Basemap</title>
  <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
  
  <!-- lets load Leaflet's .js and .css from CDN-->
  <link rel="stylesheet" href="../leaflet/leaflet.css" />
  <script src="../leaflet/leaflet.js"></script>

  <!-- Load Esri Leaflet from CDN.  it has no .css stylesheet of its own, only .js -->
  <script src="../esri-leaflet-v2.1.1/dist/esri-leaflet.js"></script>
  
  <script src="../GeoPack/leaflet/package.json"></script>
  <script src="../GeoPack/leaflet/leaflet-geopackage.js"></script>
  
  
  <style>
    html,
    body,
    #map {
      height: 90%;
      width: 90%;
      margin: auto;
      padding: 10px;
    }
  </style>
</head>
<body>
    <div id="map" class="map"></div>
	
	<script src="../GeoPack/leaflet/leaflet-geopackage.js"></script>
	<script>
	
		var map = L.map('map', {
			center: [44.66, -63.61],
			zoom: 15
		});
		var esriStreets = L.esri.basemapLayer('Streets').addTo(map);
		
		// Load the Rivers GeoPackage and display the tile layer
			L.geoPackageTileLayer({
			geoPackageUrl: '../GeoPack/leaflet/rivers.gpkg',
			layerName: 'rivers_tiles'
		}).addTo(map);
		
		// Load the Rivers GeoPackage and display the feature layer
		L.geoPackageFeatureLayer([], {
			geoPackageUrl: "../GeoPack/leaflet/rivers.gpkg",
			layerName: 'rivers'
		}).addTo(map);
		
	</script>
</body>
</html>
```

**Comment by MCR01** [comment]
Hello Daniel,

Thank you very much that code works without needing npm installed.

The only issue I am having now is trying to get the:
`geoPackageUrl: 'rivers.gpkg',`
to load local file rather than web file. (The file is located in the leaflet folder with the rest of the files)

 I feel stupid cause it should be easy but for the life of me I cannot get it to work. Java is not my strong suit.... Still learning.

Thanks again,

**Comment by danielbarela** [comment]
![screen shot 2017-09-22 at 10 12 28 am](https://user-images.githubusercontent.com/1648929/30754090-97adba3a-9f7e-11e7-89f9-cf8ce6570aeb.png)
If you are loading your index.html page in the browser from a local file I would imagine that you are getting a Cross Origin request error.  You cannot load files (in most browsers) from locally loaded html files.  You can, however, start an http server on your machine and serve your index.html page from there ie (http://localhost:<whatever port>/index.html) which will allow you to load the GeoPackage from the folder you specified.

**Comment by MCR01** [comment]
Thank you very much :) Seems to be working now.
