### ISSUE TITLE
NGA NSG PROFILE

### ISSUE THREAD

**Issue by techmavengeospatial** [ngageoint/geopackage-js#97]
Has geopackage-js and leaflet plugin been updated to support NGA NSG TILING SCHEMA/profile?

**Comment by geospatialmapmashup** [comment]
It would be great to have support the NGA's NSG GeoPackage Tiling Profile Specification?  (NSG) GeoPackage Encoding Standard 2.0
Interoperability Standard
(2016-09-14)

**Comment by bosborn** [comment]
Please see ngageoint/GeoPackage#4
